### ISSUE TITLE
Exception: mscorlib => Requested value 'inghomepay' was not found.

### ISSUE THREAD

**Issue by Sippelberg** [I-Synergy/Mollie.Net#13]
2019-08-13 17:54:21  WebShop_Payment.TreatStatusChange for paymentId tr_mEVN5s7xSS -  Failed
Exception: mscorlib => Requested value 'inghomepay' was not found.
--- StackTrace ---
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Mollie.Converters.PaymentResponseConverter.GetPaymentMethod(JObject jObject)
   at Mollie.Converters.PaymentResponseConverter.Create(Type objectType, JObject jObject)
   at Mollie.Converters.JsonCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Mollie.Clients.Base.ClientBase.<ExecuteRequestAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mollie.Clients.Base.ClientBase.<GetAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebAPI.Models.WebShop_Payment.<StatusChange>d__50.MoveNext() in C:\stadium\WebAPI\Models\WebShop_Payment.cs:line 408
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebAPI.Models.WebShop_Payment.<TreatStatusChange>d__9.MoveNext() in C:\stadium\WebAPI\Models\WebShop_Payment.cs:line 234

**Comment by IsmailHassani** [comment]
We've updated our code to the latest version of Mollie v2 where "inghomepay" was added
